---

- name: Create database
  mysql_db:
    login_user: root
    login_password: "{{ MARIADB_ROOT }}"
    name: neutron
    state: present

- name: create user neutron
  shell: mysql -uroot -pmysql -ne "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'{{ item }}' IDENTIFIED BY '{{ NEUTRON_DBPASS }}'"
  with_items:
  - "localhost"
  - "%"

- block:
  - name: Create the neutron user
    os_user:
      state: present
      name: neutron
      password: "{{ NEUTRON_PASS }}"
      domain: default

  - name: Add the admin role to the neutron user and service project
    os_user_role:
      user: neutron
      role: admin
      project: service      

  - name: Create the neutron service entity
    os_keystone_service:
      state: present
      name: neutron
      service_type: network
      description: OpenStack Networking

  - name: Create the neutron service API endpoints
    shell: |
      openstack endpoint create --region RegionOne network public http://controller:9696
      openstack endpoint create --region RegionOne network internal http://controller:9696
      openstack endpoint create --region RegionOne network admin http://controller:9696

  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ ADMIN_PASS }}"
    OS_AUTH_URL: http://controller:35357/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2


- name: install the packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - openstack-neutron
  - openstack-neutron-ml2
  - openstack-neutron-linuxbridge
  - ebtables

- include: provider.yml
  when: provider

- include: selfservice.yml
  when: selfservice

- name: Edit the /etc/neutron/metadata_agent.ini
  ini_file:
    path: /etc/neutron/metadata_agent.ini
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'DEFAULT', option: 'nova_metadata_ip', value: 'controller' }
  - { section: 'DEFAULT', option: 'metadata_proxy_shared_secret', value: '{{ METADATA_SECRET }}' }

- name: Edit /etc/nova/nova.conf
  ini_file:
    path: /etc/nova/nova.conf
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'neutron', option: 'url', value: 'http://controller:9696' }
  - { section: 'neutron', option: 'auth_url', value: 'http://controller:35357' }
  - { section: 'neutron', option: 'auth_type', value: 'password' }
  - { section: 'neutron', option: 'project_domain_name', value: 'default' }
  - { section: 'neutron', option: 'user_domain_name', value: 'default' }
  - { section: 'neutron', option: 'region_name', value: 'RegionOne' }
  - { section: 'neutron', option: 'project_name', value: 'service' }
  - { section: 'neutron', option: 'username', value: 'neutron' }
  - { section: 'neutron', option: 'password', value: '{{ NEUTRON_PASS }}' }
  - { section: 'neutron', option: 'service_metadata_proxy', value: 'true' }
  - { section: 'neutron', option: 'metadata_proxy_shared_secret', value: '{{ METADATA_SECRET }}' }

- name:  initialization scripts expect a symbolic link
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: Populate the Image service database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become: true
  become_method: su
  become_user: neutron
  become_flags: '-s /bin/sh'

- name: Restart the Compute API service
  service:
    name: openstack-nova-api
    state: restarted

- name: Start the Networking services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Start the l3 agent
  service: 
    name: "{{ item }}"
    state: started
    enable: yes
  with_items:
  - neutron-l3-agent
  when: selfservice
