---
- name: Edit neutron.conf
  ini_file:
    path: /etc/neutron/neutron.conf
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'database', option: 'connection',value: 'mysql+pymysql://neutron:{{ NEUTRON_DBPASS }}@controller/neutron' }
  - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
  - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
  - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'true' }
  - { section: 'DEFAULT', option: 'transport_url ', value: 'rabbit://openstack:{{ RABBIT_PASS }}@controller' }
  - { section: 'DEFAULT', option: 'auth_strategy',value: 'keystone' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes',value: 'true' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes',value: 'true' }

  - { section: 'keystone_authtoken', option: 'auth_uri',value: 'http://controller:5000' }
  - { section: 'keystone_authtoken', option: 'auth_url',value: 'http://controller:35357' }
  - { section: 'keystone_authtoken', option: 'memcached_servers',value: 'controller:11211' }
  - { section: 'keystone_authtoken', option: 'auth_type',value: 'password' }
  - { section: 'keystone_authtoken', option: 'project_domain_name',value: 'default' }
  - { section: 'keystone_authtoken', option: 'user_domain_name',value: 'default' }
  - { section: 'keystone_authtoken', option: 'project_name',value: 'service' }
  - { section: 'keystone_authtoken', option: 'username',value: 'neutron' }
  - { section: 'keystone_authtoken', option: 'password',value: '{{ NEUTRON_PASS }}' }
  - { section: 'nova', option: 'region_name',value: 'RegionOne' }
  - { section: 'nova', option: 'auth_url',value: 'http://controller:35357' }
  - { section: 'nova', option: 'auth_type',value: 'password' }
  - { section: 'nova', option: 'project_domain_name',value: 'default' }
  - { section: 'nova', option: 'user_domain_name',value: 'default' }
 - { section: 'nova', option: 'project_name',value: 'service' }
  - { section: 'nova', option: 'username',value: 'nova' }
  - { section: 'nova', option: 'password',value: '{{ NOVA_PASS }}' }

  - { section: 'oslo_concurrency', option: 'lock_path', value: '/var/lib/neutron/tmp' }

- name: Edit the ml2_conf.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'ml2', option: 'type_drivers',value: 'flat,vlan,vxlan' }
  - { section: 'ml2', option: 'tenant_network_types',value: 'vxlan' }
  - { section: 'ml2', option: 'mechanism_drivers',value: 'linuxbridge,l2population' }
  - { section: 'ml2', option: 'extension_drivers',value: 'port_security' }
  - { section: 'ml2_type_flat', option: 'flat_networks',value: 'provider' }
  - { section: 'ml2_type_vxlan', option: 'vni_ranges',value: '1:1000' }
  - { section: 'securitygroup', option: 'enable_ipset',value: 'true' }

- name: Edit the linuxbridge_agent.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'linux_bridge', option: 'physical_interface_mappings',value: 'provider:{{ PROVIDER_INTERFACE_NAME }}' }
  - { section: 'vxlan', option: 'enable_vxlan',value: 'true' }
  - { section: 'vxlan', option: 'local_ip',value: '{{ OVERLAY_INTERFACE_IP_ADDRESS }}' }
  - { section: 'vxlan', option: 'l2_population',value: 'true' }
  - { section: 'securitygroup', option: 'enable_security_group',value: 'true' }
  - { section: 'securitygroup', option: 'firewall_driver',value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }

- name: Edit the /etc/neutron/l3_agent.ini
  ini_file:
    path: /etc/neutron/l3_agent.ini
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'DEFAULT', option: 'interface_driver', value: 'linuxbridge' }

- name: Edit the /etc/neutron/dhcp_agent.ini
  ini_file:
    path: /etc/neutron/dhcp_agent.ini
    section:  "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'DEFAULT', option: 'interface_driver', value: 'linuxbridge' }
  - { section: 'DEFAULT', option: 'dhcp_driver', value: 'neutron.agent.linux.dhcp.Dnsmasq' }
  - { section: 'DEFAULT', option: 'enable_isolated_metadata', value: 'true' }

