---

- name: Add openstack repository
  yum_repository:
    name: centos-release-openstack-ocata
    state: present

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install openstack package
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    python-openstackclient
    openstack-selinux
